name: Tests
on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: install
        run: npm ci

      - name: generate-version
        run: npm run generate-version

      - name: test
        run: npm run test
